FROM nginx
LABEL probando el keyword label
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 6070
CMD ["nginx", "-g", "daemon off;"]
#USER 405 Por algun motivo da error node. Ver de que manera se puede securizar.

